models:
  - name: stg_customers
    description: "Customer information"
    columns:
      - name: customer_id
        data_type: string
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: customer_unique_id
        data_type: string
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: customer_zip_code_prefix
        data_type: int64

      - name: customer_state
        data_type: string

      - name: customer_city
        data_type: string