sources:
  - name: ecommerce
    database: smiling-audio-448313-p0
    schema: ecommerce
    tables:
      - name: customers
      - name: orders
      - name: products
      - name: sellers
      - name: order_items
      - name: order_payments
      - name: order_reviews
      - name: geolocation
      - name: product_category_name_translation